set -g default-terminal "screen-256color"
set-option -ga terminal-overrides ",screen-256color:Tc,xterm-256color:Tc"
set-option -sg escape-time 100

# vi key maps
#
setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

set -sg escape-time 0

# custom key maps
#
bind t split-window -v -p 25 -c "#{pane_current_path}"
bind r source-file ~/.config/tmux/tmux.conf

# plugins
#
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-battery'

# %hidden MODULE_NAME="kubectx"
# set -g  "@catppuccin_kubectx_icon"  "󱃾 "
# set -gF "@catppuccin_kubectx_color" "#326CE5"
# set -g  "@catppuccin_kubectx_text"  "#(~/.config/tmux/scripts/kubectx.sh)"

# set -gF status-right "#[fg=#326CE5,#[fg=#{@thm_crust}] 󱃾 #(~/.config/tmux/scripts/kubectx.sh)"

set -g @catppuccin_window_status_style "rounded"

# load catppuccin
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# status line
set -g status-left ""
set -g status-right-length 100
set -g status-left-length 100

set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -agF status-right "#{E:@catppuccin_status_battery}"
set -ag status-right "#[fg=#326CE5,bg=#{E:@_ctp_status_bg}]#[fg=#{E:@thm_crust},bg=#326CE5] 󱃾 #(~/.config/tmux/scripts/kubectx.sh) #[fg=#{E:@_ctp_status_bg},bg=#326CE5]"

run '~/.config/tmux/plugins/tpm/tpm'
